#
# MAINTAINER            k7zy <acesu@outlook.com>
# DOCKER-VERSION        17.05 
#
FROM ubuntu
MAINTAINER k7zy     <acesu@outlook.com>


RUN apt-get update  && \
    apt-get upgrade -y && \
    apt-get  install nodejs && \
    npm install -g Brosec


